### ISSUE TITLE
Thanks, a nice simple complete socket implemention

### ISSUE THREAD

**Issue by GerritKuilder** [leen-neel/socket-io-chat#1]
Hello,

thanks for this, I was forced to rewrite a big app (I crashed it), from muxt to quasar/vue3 and this will help me to properly implement the web socket part.

Works out of the box. Nearly, had to modify the ports and cors as I was running it from another machine.
KR,

Gerrit Kuilder

**Comment by leen-neel** [comment]
Greetings! Glad this could be of use. Keep in mind that this uses an old version of Quasar 2. I'll update this as soon as I can. Let me know if you face any issues!

Best,
Neel.

**Comment by GerritKuilder** [comment]
My quasar versions:
 » Pkg quasar................ v2.11.5
 » Pkg @quasar/app-webpack... v3.7.1
 » Transpiled JS............. yes (Babel)

No problems using your quasar code in my implementation, nothing to change on the back end.

Thanks again

**Comment by leen-neel** [comment]
Amazing! Happy to help!
